/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as YamlJsonImport } from './routes/yaml-json'
import { Route as YamlFmtImport } from './routes/yaml-fmt'
import { Route as WebBeautifyImport } from './routes/web-beautify'
import { Route as UrlViewerImport } from './routes/url-viewer'
import { Route as SqlFmtImport } from './routes/sql-fmt'
import { Route as OpenapiImport } from './routes/openapi'
import { Route as JwtDecodeImport } from './routes/jwt-decode'
import { Route as JsonnetImport } from './routes/jsonnet'
import { Route as JsonFmtImport } from './routes/json-fmt'
import { Route as HtmlViewerImport } from './routes/html-viewer'
import { Route as Base64Import } from './routes/base64'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const YamlJsonRoute = YamlJsonImport.update({
  id: '/yaml-json',
  path: '/yaml-json',
  getParentRoute: () => rootRoute,
} as any)

const YamlFmtRoute = YamlFmtImport.update({
  id: '/yaml-fmt',
  path: '/yaml-fmt',
  getParentRoute: () => rootRoute,
} as any)

const WebBeautifyRoute = WebBeautifyImport.update({
  id: '/web-beautify',
  path: '/web-beautify',
  getParentRoute: () => rootRoute,
} as any)

const UrlViewerRoute = UrlViewerImport.update({
  id: '/url-viewer',
  path: '/url-viewer',
  getParentRoute: () => rootRoute,
} as any)

const SqlFmtRoute = SqlFmtImport.update({
  id: '/sql-fmt',
  path: '/sql-fmt',
  getParentRoute: () => rootRoute,
} as any)

const OpenapiRoute = OpenapiImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => rootRoute,
} as any)

const JwtDecodeRoute = JwtDecodeImport.update({
  id: '/jwt-decode',
  path: '/jwt-decode',
  getParentRoute: () => rootRoute,
} as any)

const JsonnetRoute = JsonnetImport.update({
  id: '/jsonnet',
  path: '/jsonnet',
  getParentRoute: () => rootRoute,
} as any)

const JsonFmtRoute = JsonFmtImport.update({
  id: '/json-fmt',
  path: '/json-fmt',
  getParentRoute: () => rootRoute,
} as any)

const HtmlViewerRoute = HtmlViewerImport.update({
  id: '/html-viewer',
  path: '/html-viewer',
  getParentRoute: () => rootRoute,
} as any)

const Base64Route = Base64Import.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/base64': {
      id: '/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof Base64Import
      parentRoute: typeof rootRoute
    }
    '/html-viewer': {
      id: '/html-viewer'
      path: '/html-viewer'
      fullPath: '/html-viewer'
      preLoaderRoute: typeof HtmlViewerImport
      parentRoute: typeof rootRoute
    }
    '/json-fmt': {
      id: '/json-fmt'
      path: '/json-fmt'
      fullPath: '/json-fmt'
      preLoaderRoute: typeof JsonFmtImport
      parentRoute: typeof rootRoute
    }
    '/jsonnet': {
      id: '/jsonnet'
      path: '/jsonnet'
      fullPath: '/jsonnet'
      preLoaderRoute: typeof JsonnetImport
      parentRoute: typeof rootRoute
    }
    '/jwt-decode': {
      id: '/jwt-decode'
      path: '/jwt-decode'
      fullPath: '/jwt-decode'
      preLoaderRoute: typeof JwtDecodeImport
      parentRoute: typeof rootRoute
    }
    '/openapi': {
      id: '/openapi'
      path: '/openapi'
      fullPath: '/openapi'
      preLoaderRoute: typeof OpenapiImport
      parentRoute: typeof rootRoute
    }
    '/sql-fmt': {
      id: '/sql-fmt'
      path: '/sql-fmt'
      fullPath: '/sql-fmt'
      preLoaderRoute: typeof SqlFmtImport
      parentRoute: typeof rootRoute
    }
    '/url-viewer': {
      id: '/url-viewer'
      path: '/url-viewer'
      fullPath: '/url-viewer'
      preLoaderRoute: typeof UrlViewerImport
      parentRoute: typeof rootRoute
    }
    '/web-beautify': {
      id: '/web-beautify'
      path: '/web-beautify'
      fullPath: '/web-beautify'
      preLoaderRoute: typeof WebBeautifyImport
      parentRoute: typeof rootRoute
    }
    '/yaml-fmt': {
      id: '/yaml-fmt'
      path: '/yaml-fmt'
      fullPath: '/yaml-fmt'
      preLoaderRoute: typeof YamlFmtImport
      parentRoute: typeof rootRoute
    }
    '/yaml-json': {
      id: '/yaml-json'
      path: '/yaml-json'
      fullPath: '/yaml-json'
      preLoaderRoute: typeof YamlJsonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/html-viewer': typeof HtmlViewerRoute
  '/json-fmt': typeof JsonFmtRoute
  '/jsonnet': typeof JsonnetRoute
  '/jwt-decode': typeof JwtDecodeRoute
  '/openapi': typeof OpenapiRoute
  '/sql-fmt': typeof SqlFmtRoute
  '/url-viewer': typeof UrlViewerRoute
  '/web-beautify': typeof WebBeautifyRoute
  '/yaml-fmt': typeof YamlFmtRoute
  '/yaml-json': typeof YamlJsonRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/html-viewer': typeof HtmlViewerRoute
  '/json-fmt': typeof JsonFmtRoute
  '/jsonnet': typeof JsonnetRoute
  '/jwt-decode': typeof JwtDecodeRoute
  '/openapi': typeof OpenapiRoute
  '/sql-fmt': typeof SqlFmtRoute
  '/url-viewer': typeof UrlViewerRoute
  '/web-beautify': typeof WebBeautifyRoute
  '/yaml-fmt': typeof YamlFmtRoute
  '/yaml-json': typeof YamlJsonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/html-viewer': typeof HtmlViewerRoute
  '/json-fmt': typeof JsonFmtRoute
  '/jsonnet': typeof JsonnetRoute
  '/jwt-decode': typeof JwtDecodeRoute
  '/openapi': typeof OpenapiRoute
  '/sql-fmt': typeof SqlFmtRoute
  '/url-viewer': typeof UrlViewerRoute
  '/web-beautify': typeof WebBeautifyRoute
  '/yaml-fmt': typeof YamlFmtRoute
  '/yaml-json': typeof YamlJsonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base64'
    | '/html-viewer'
    | '/json-fmt'
    | '/jsonnet'
    | '/jwt-decode'
    | '/openapi'
    | '/sql-fmt'
    | '/url-viewer'
    | '/web-beautify'
    | '/yaml-fmt'
    | '/yaml-json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base64'
    | '/html-viewer'
    | '/json-fmt'
    | '/jsonnet'
    | '/jwt-decode'
    | '/openapi'
    | '/sql-fmt'
    | '/url-viewer'
    | '/web-beautify'
    | '/yaml-fmt'
    | '/yaml-json'
  id:
    | '__root__'
    | '/'
    | '/base64'
    | '/html-viewer'
    | '/json-fmt'
    | '/jsonnet'
    | '/jwt-decode'
    | '/openapi'
    | '/sql-fmt'
    | '/url-viewer'
    | '/web-beautify'
    | '/yaml-fmt'
    | '/yaml-json'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Base64Route: typeof Base64Route
  HtmlViewerRoute: typeof HtmlViewerRoute
  JsonFmtRoute: typeof JsonFmtRoute
  JsonnetRoute: typeof JsonnetRoute
  JwtDecodeRoute: typeof JwtDecodeRoute
  OpenapiRoute: typeof OpenapiRoute
  SqlFmtRoute: typeof SqlFmtRoute
  UrlViewerRoute: typeof UrlViewerRoute
  WebBeautifyRoute: typeof WebBeautifyRoute
  YamlFmtRoute: typeof YamlFmtRoute
  YamlJsonRoute: typeof YamlJsonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Base64Route: Base64Route,
  HtmlViewerRoute: HtmlViewerRoute,
  JsonFmtRoute: JsonFmtRoute,
  JsonnetRoute: JsonnetRoute,
  JwtDecodeRoute: JwtDecodeRoute,
  OpenapiRoute: OpenapiRoute,
  SqlFmtRoute: SqlFmtRoute,
  UrlViewerRoute: UrlViewerRoute,
  WebBeautifyRoute: WebBeautifyRoute,
  YamlFmtRoute: YamlFmtRoute,
  YamlJsonRoute: YamlJsonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/base64",
        "/html-viewer",
        "/json-fmt",
        "/jsonnet",
        "/jwt-decode",
        "/openapi",
        "/sql-fmt",
        "/url-viewer",
        "/web-beautify",
        "/yaml-fmt",
        "/yaml-json"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/base64": {
      "filePath": "base64.tsx"
    },
    "/html-viewer": {
      "filePath": "html-viewer.tsx"
    },
    "/json-fmt": {
      "filePath": "json-fmt.tsx"
    },
    "/jsonnet": {
      "filePath": "jsonnet.tsx"
    },
    "/jwt-decode": {
      "filePath": "jwt-decode.tsx"
    },
    "/openapi": {
      "filePath": "openapi.tsx"
    },
    "/sql-fmt": {
      "filePath": "sql-fmt.tsx"
    },
    "/url-viewer": {
      "filePath": "url-viewer.tsx"
    },
    "/web-beautify": {
      "filePath": "web-beautify.tsx"
    },
    "/yaml-fmt": {
      "filePath": "yaml-fmt.tsx"
    },
    "/yaml-json": {
      "filePath": "yaml-json.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
